name: Executar Bot de Vagas

on:
  schedule:
    - cron: '0 12,17 * * *'
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        # Removemos o mattermostdriver, agora usamos só requests (mais leve)
        run: pip install requests beautifulsoup4 python-dotenv

      - name: Executar Script
        env:
          # AQUI ESTÁ A MUDANÇA: Usando o nome que você criou
          MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
        run: python README.py
